### ISSUE TITLE
useParentReuse does not respects parent reuse

### ISSUE THREAD

**Issue by dvabuzyarov** [dadhi/DryIoc#295] opened 2020-07-22 15:17 UTC
DryIoc.dll : 4.2.5
.net core 3.1

``` c#
[TestClass]
    public class DispatcherUnitTests
    {
        [TestMethod]
        public void RespectsParentReuse()
        {
            var openResolutionScope = Setup.With(openResolutionScope: true);

            var container = new Container();
            container.Register<Car, Car>(Reuse.Scoped, setup: openResolutionScope);
            container.Register<Engine, Engine>(setup: Setup.With(useParentReuse: true));
            
            container.Register<Replicator, Replicator>(Reuse.Transient);
            // energy should respect the replicator transient reuse
            container.Register<Energy, Energy>(setup: Setup.With(useParentReuse: true));

            var car1 = container.Resolve<Car>();
            var car2 = container.Resolve<Car>();
            var engine1 = car1.Engine.Replicator.CreateTransientEngine();
            var engine2 = car1.Engine.Replicator.CreateTransientEngine();
            
            Assert.AreNotSame(car1.Engine.Replicator.Energy, car2.Engine.Replicator.Energy);
            Assert.AreNotSame(engine1, engine2);
            // Failed
            Assert.AreNotSame(car1.Engine.Replicator.Energy, engine1.Replicator.Energy);
            // Failed
            Assert.AreNotSame(engine1.Replicator.Energy, engine2.Replicator.Energy);
        }
    }

    class Car
    {
        public Engine Engine { get; }

        public Car(Engine engine)
        {
            Engine = engine;
        }
    }

    class Engine
    {
        public Replicator Replicator { get; }

        public Engine(Replicator replicator)
        {
            Replicator = replicator;
        }
    }

    class Replicator
    {
        public IContainer Container { get; }
        public Energy Energy { get; }

        public Replicator(IContainer container, Energy energy)
        {
            Container = container;
            Energy = energy;
        }

        public Engine CreateTransientEngine()
        {
            return Container.Resolve<Engine>();
        }
    }

    class Energy
    {
    }
```

The energy is requested with a transient service, but in the provided case it use a different reuse.

**Comment by dadhi** [comment] 2020-07-23 07:08
Hi, thanks for the tests. Will check when time permits.

**Comment by dadhi** [comment] 2020-07-25 19:02
@dvabuzyarov Hi again,

Apparently, the test does not work by design - though it may be confusing given the `useParentReuse` name.
Here is the doc - https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ReuseAndScopes.md#setupuseparentreuse

So the question is what to do with it, given that I don't want to break the current users. 
I may add the `useParentReuseEvenTransient` to cover the case in question. Seems like the option name is explaining itself better than the original one.

**Comment by dvabuzyarov** [comment] 2020-07-26 20:31
Hmm.. according to the doc Energy should have transient reuse since Replicator (the parent) has it. But in the test we can see that different instances of Replicators got the same instance of Energy.

**Comment by dadhi** [comment] 2020-07-26 20:44
Ok, the docs somewhat confusing.. will fix.

> This option allows the dependency to use parent or ancestor service reuse (if it has parents defining a reuse).

The Transient is basically an absense of the reuse, the same as no reuse at all. So if parent does not define reuse (same as Transient) it will be skipped until Scoped or Singleton ancestor found. Or if nothing found...

> In case of all parents are transient or dependency is wrapped in Func somewhere in parents chain, the dependency will be transient at the end.

**Comment by dvabuzyarov** [comment] 2020-07-26 20:50
Ok, thanks. I thought that Transient is one of reuse rules. The last question: what reuse is getting Engine in the following code 
``` c#
Container.Resolve<Engine>()
```
Is it equal to Func factory?

**Comment by dadhi** [comment] 2020-07-26 20:54
Updated the docs...

The `Engine` is Transient because there is no parent here - it is a resolution root.

**Comment by dvabuzyarov** [comment] 2020-07-26 21:21
Ok, so in this case ``` c# Container.Resolve<Engine>() ``` Engine is transient, its child (Replicator) is transient and its child (Energy) in its turn is also transient, so Energy instances should be different all the time. And the assertion should not failed.

**Comment by dadhi** [comment] 2020-07-26 22:44
You are right. This is the cache problem :( 
`Engine` is injected into `Car` as Scoped because `Car` is Scoped.
Then it resolved directly as Transient but still cached as Scoped.
Looking...

**Comment by dadhi** [comment] 2020-07-26 23:02
Oh no, it much more interesting... stay tuned.

**Comment by dvabuzyarov** [comment] 2020-07-27 05:57
It sounds intriguing ;-). Awaiting for updates.

**Comment by dadhi** [comment] 2020-07-27 07:33
@dvabuzyarov 

First, I don't have a solution in mind currently :/
So I will try to explain the problem here and maybe will get the idea by the end.

### Explanation train

The test resolves the `Car` with injecting the `Engine -> Replicator -> Energy` dependency chain.
`Engine` and `Energy` are scoped because they are using a parent (ancestor) reuse which is Scoped for `Engine`.


A couple of implementation details about `useParentReuse` services:

1. The service expression is not cached
2. The service is injected into the parent expression as resolution call

The 2 point is important here. First injecting service as resolution call allows replacing the dependency in
expression later without invalidating the cached parent expression. 
**First ding-dong here** - I am not sure that replace-ability is important for `useParentReuse` services.

Next, the important fact about as resolution call injection is that it contains **whole ancestors recorded in the request passed to the Resolve call** in order for conditional injection, recursive and captive dependency checks to work.
In our case `Energy` will be injected as pseudocode
```cs
Resolve<Energy>(..., Request.Create().Push<Car>().Push<Engine>().Push<Replicator>())
```

When resolving `Energy` DryIoc will navigate the request to find the first non-transient parent which is `Engine`.

The problem is raised later when we resolving `Engine` separately (which is not cached), then `Replicator` is injected into it **which is cached because it Transient**.
Now... the `Replicator` expression contains the `Resolve` call for `Energy` which still contains the full request up to `Car` recorded. The request records the reuses as well - **so the Engine is still recorded as Scoped here so the `Energy` is resolved as Scoped**. Duh!


### And I'm still don't have a solution 

I need more info, so will try to remove injection as a resolution call first to see what tests are failing.

**Comment by dvabuzyarov** [comment] 2020-07-27 09:39
At the moment I barely following you since don't know under the hood details. I need much more time to figure out how the container works internally. At least I can test the solution and provide feedback. ;-)

**Comment by dadhi** [comment] 2020-07-31 07:41
Here is a working variant - will work when v4.3.0 is released.

```cs
   c.Register<Replicator>(Reuse.Transient, setup: Setup.With(asResolutionCall: true));
```

The `Replicator` with `asResolutionCall` is required to avoid caching problems when the `Replicator` is resolved both as a dependency and **as a resolution root** for the situation when you have a conditional behavior like this one (with `parentReuse` making the dependency reuse conditionally depend on the ancestor's chain).

```cs
        [Test]
        public void RespectsParentReuse()
        {
            var c = new Container();
            c.Register<Car>(Reuse.Scoped, setup: Setup.With(openResolutionScope: true));

            c.Register<Engine>(setup: Setup.With(useParentReuse: true)); // Scoped when injected in Car

            // WORKS!: this does work but requires you to know how to specify no-caching, and maybe it is a good thing.
            //c.Register(typeof(Replicator), 
            //    new ReflectionFactory(typeof(Replicator), Reuse.Transient) { Caching = FactoryCaching.DoNotCache });

            // DOES NOT WORK!
            // Hmm, the question though - does asResolutionCall prevents caching, ahahahaaa - NO~!
            // So, let's see what happens when we disable the caching for IsResolutionCall - WORKS!
            c.Register<Replicator>(Reuse.Transient, setup: Setup.With(asResolutionCall: true));

            c.Register<Energy>(setup: Setup.With(useParentReuse: true)); // Scoped when injected in Engine

            var car1 = c.Resolve<Car>();
            var car2 = c.Resolve<Car>();
            var engine1 = car1.Engine.Replicator.CreateTransientEngine();
            var engine2 = car1.Engine.Replicator.CreateTransientEngine();

            Assert.AreNotSame(car1, car2);
            Assert.AreNotSame(engine1, engine2);
            Assert.AreNotSame(engine1.Replicator, engine2.Replicator);
            Assert.AreNotSame(engine1.Replicator.Energy, engine2.Replicator.Energy);
        }
```

**Comment by dadhi** [comment] 2020-07-31 07:41
fixed

**Closed by dadhi** 2020-07-31 07:41 UTC
Labels: bug
