### ISSUE TITLE
Singleton register type has create twice object in memory.

### ISSUE THREAD

**Issue by Enlil26** [dadhi/DryIoc#337] opened 2020-10-16 07:56 UTC
I don't no why and if i use well Dryioc.

- a container:
`protected readonly DryIoc.Container container = new DryIoc.Container(r => r.WithoutThrowOnRegisteringDisposableTransient());`

- register :
`container.Register(typeof(Interface), typeof(Implementation), reuse: Reuse.Singleton, ifAlreadyRegistered: IfAlreadyRegistered.Replace);`

- resolve :
` container.Resolve<Interface>(ifUnresolved:IfUnresolved.Throw);`

But in memory in heavy application with dotMemory i see 2 instance of this singleton register object in my container

![image](https://user-images.githubusercontent.com/6853888/96227964-2f1e7100-0f95-11eb-9cba-4ae9adeb31ac.png)

How i can fix that ? i really don't want use singleton structure class with after register singleton intance in Dryioc.

**Comment by dadhi** [comment] 2020-10-16 08:13
@Enlil26 
What is the DryIoc version?
From the picture I see the two references but not the two instances. Did you have a confirmation that it is the latter case?

**Comment by Enlil26** [comment] 2020-10-16 08:49
@dadhi 

Version 4.0.5
```
 <PackageReference Include="DryIoc.dll">
      <Version>4.0.5</Version>
    </PackageReference>
```

I see exactly 2 instances 

![image](https://user-images.githubusercontent.com/6853888/96236943-f84c5900-0f9c-11eb-8a04-9a064cb26bd6.png)

thank you for your attention

**Comment by dadhi** [comment] 2020-10-16 09:43
@Enlil26 I see,

The version 4.0.5 was realeased a quite some time ago, but more notably there were a lot of changes in how the singletons are handled since then https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/VersionHistory.md#v405-release-notes--2019-06-08

So I would suggest you to update to v4.5.0 and check if error is reproduced.

**Comment by Enlil26** [comment] 2020-10-16 13:10
@dadhi 
I have update to version 4.5.0 but i have the same behavior.
just to be sure i have add in constructor a log message with increment this constructor are effectively call twice

```
        private static int nbInst = 0;
        public ILDictionnaireFr()
        {
            Logs.Debug($"Instance {nbInst++}");
        }
```
16/10/2020 14:39:29 : Instance 0
16/10/2020 14:40:42 : Instance 1

![image](https://user-images.githubusercontent.com/6853888/96261975-6b67c680-0fc1-11eb-8bc0-1e75caa742a6.png)


![image](https://user-images.githubusercontent.com/6853888/96261454-c5b45780-0fc0-11eb-944a-2a37c68b437e.png)

**Comment by dadhi** [comment] 2020-10-16 14:50
@Enlil26 Now it is interesting.

Ideally I would like to have a small reproducible test...

For the sanity check I will test it locally with the options you are using for the case. But I already have a massively parallel tests which create singletons and they are passing fine for a long time.

I guess there is a some nuance in your setup or the resolve pattern which surfaces the problem.
So I would like to get as much as possible info from you.

**Comment by dadhi** [comment] 2020-10-18 16:18
@Enlil26 

I have added the [test](https://github.com/dadhi/DryIoc/issues/337) but the issue is not reproducible.

Could you please check the test and examine if I am missing anything.

**Comment by Enlil26** [comment] 2020-10-20 06:58
@dadhi 
i'll try to reproduce in your test.

I have test in my application when I Resolve() just after Register() it work well with this call stack:
![image](https://user-images.githubusercontent.com/6853888/96550315-ff32de80-12b0-11eb-964a-9528f29bc39c.png)

and return my singleton by cachedDelagate
![image](https://user-images.githubusercontent.com/6853888/96550424-21c4f780-12b1-11eb-8ecc-89a649f0a834.png)

Later in my app when i Resolve() don't retrieve my object with this call stack:
![image](https://user-images.githubusercontent.com/6853888/96550651-694b8380-12b1-11eb-8939-21d83daa18d5.png)
 and lg 323 entry.values == null so no cachedDelagate and create object again
![image](https://user-images.githubusercontent.com/6853888/96550787-98fa8b80-12b1-11eb-8ddb-49805e0610c0.png)

**Comment by dadhi** [comment] 2020-10-20 13:23
@Enlil26 

Thanks for the info... I am not yet sure how it relates but we will figure.

>  entry.values == null so no cachedDelagate and create object again

It should not create the object anyway, because it is just a cache for fast access - if you drop the cache, the object won't be recreated because it is stored in the SingletonScope in the separate map.

Anyway, the situation with the missing the cache for the second time is strange. 
Once in a cache, it should always stay there until you Replace the registration or intentionally Unregister it. 

- So by any chance, are you doing twice the registration?
```cs
container.Register(typeof(Interface), typeof(Implementation), reuse: Reuse.Singleton, ifAlreadyRegistered: IfAlreadyRegistered.Replace);
``` 

- Why are you using the `ifAlreadyRegistered: IfAlreadyRegistered.Replace` option?
Maybe try to change it to `ifAlreadyRegistered: IfAlreadyRegistered.Keep` to check the results.

**Comment by Enlil26** [comment] 2020-10-26 14:49
@dadhi 
actually I register 2 time with IfAlreadyRegistered.Replace like that:
`                  
        [TestFixture]
        public class GHIssue337_Singleton_is_created_twice
        {
            [Test]
            public void Test()
            {

                DryIoc.Container container = new DryIoc.Container(r => r.WithoutThrowOnRegisteringDisposableTransient());

                container.Register(typeof(IAbc), typeof(Abc), reuse: Reuse.Singleton, ifAlreadyRegistered:  IfAlreadyRegistered.Replace);

                container.Resolve<IAbc>(ifUnresolved: IfUnresolved.Throw);

                container.Register(typeof(IAbc), typeof(Abc), reuse: Reuse.Singleton, ifAlreadyRegistered: IfAlreadyRegistered.Replace);

                container.Resolve<IAbc>(ifUnresolved: IfUnresolved.Throw);

            }

            class Abc: IAbc
            {
                public static int Counter;
                public Abc()
                {
                    Thread.Sleep(100);
                    Console.WriteLine(++Counter);
                }
            }
            interface IAbc
            {

            }

        }
`

I will change my code but why Dryioc keep reférence with first object in memory ?

**Comment by dadhi** [comment] 2020-10-26 15:40
@Enlil26 You mean why the previous sintleton is still not removed?

The replacing registration is similar to removing (unregistering) the previous registration and registering a new. So here is the relevant document subtopic: https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/UnregisterAndResolutionCache.md#unregister-and-reused-services

I suggest you to also read the whole document.

The feature maybe considered as a limitation or otherwise maybe considered as prevention of undefined behavior, e.g. what happens when you injected the singleton as a dependency and then trying to remove/dispose it.

If you really need this behavior I would suggest you to specifically design for it. For instance you wrap your singleton in the additional Box with the replacable Value.

**Comment by dadhi** [comment] 2020-10-26 16:54
@Enlil26 

What is the scenario when you need to replace the registration, is it to mock the dependency in the test or some plugin infra?


Btw, there is slightly different option to use the registration with `setup: Setup.With(weaklyReferenced: true)` but it won't fire the `Dispose` when GCed.

**Comment by dadhi** [comment] 2020-10-26 17:04
@Enlil26 And as usual with DryIoc non default features, your case is likely to be accomplished with Decorators: https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/Decorators.md#decorators

But I need to play with that myself to provide the concrete solution.

**Comment by dadhi** [comment] 2020-11-06 12:00
@Enlil26 Are you waiting for me or I can close the issue?

**Closed** 2020-12-10 08:04 UTC
Labels: investigation
