### ISSUE TITLE
Inconsitent transient disposable behaviour, when using 'Made'

### ISSUE THREAD

**Issue by SamNibbles** [dadhi/DryIoc#402] opened 2021-05-14 08:58 UTC
I have a service which implements `IDisposable`, this service is setup for DI with `trackDisposableTransient: true`.

The service has 1 constructor. 

With this logic the DI is not properly disposing of the service at the end of the scope, but if I add a `Made.Of` for the service, then everything gets disposed of correctly.

So this disposes correctly -
`container.Register<IService, Service>(setup: Setup.With(trackDisposableTransient: true), made: Made.Of(() => new Service(Arg.Of<Func<object, ILogger>>(), Arg.Of<IService1>(), Arg.Of<IService2>(), Arg.Of<IService3>())));`

and this doesnt -
`container.Register<IService, Service>(setup: Setup.With(trackDisposableTransient: true));`

Even thought there is only once constructor on the `Service` class, which from what I understand, means they should be identical.

I have tried my best to replicate this issue in a seperate setup but to no avail, so I completely understand it is not an easy question to answer.

Happy to provide anymore details where possible!

**Comment by dadhi** [comment] 2021-05-14 12:12
@SamNibbles Thanks for posting, will look.

**Comment by dadhi** [comment] 2021-05-17 13:23
@SamNibbles Hi, I am not able to reproduce the issue. Please look at the tests, and maybe you can add more details:
https://github.com/dadhi/DryIoc/blob/master/test/DryIoc.IssuesTests/GHIssue402_Inconsistent_transient_disposable_behavior_when_using_Made.cs

**Comment by SamNibbles** [comment] 2021-05-18 15:06
@dadhi I will take a look!

**Comment by dadhi** [comment] 2021-06-03 10:08
closing...

**Closed by dadhi** 2021-06-03 10:08 UTC
