### ISSUE TITLE
Resolve still caches args values when using factory method.

### ISSUE THREAD

**Issue by rdeago** [dadhi/DryIoc#107] opened 2019-04-02 09:55 UTC
Even after issue #29 is resolved, DryIoc v4.0.2 seems to cache values passed in the `args` parameter of Resolve when using a factory method to resolve a specific interface given a parameter.

This happens in the following situation:

- There is an interface other services depend on, whose concrete implementation requires a parameter to be specified at resolve time.

- There is a static factory class, with a method that creates an instance of said interface given a parameter.

- The interface is registered using `Made.Of`, `ServiceInfo.Of`, and `Arg.Of`, as explained [in the documentation](https://bitbucket.org/dadhi/dryioc/wiki/SelectConstructorOrFactoryMethod#markdown-header-factory-method-instead-of-constructor).

- There are two services, let's call them A and B, whose concrete implementations both depend on the above interface.

- **The container is initialized with a default reuse of `Singleton` or `ScopedOrSingleton`.** (If the container has the default rules, everything works as expected)

- We first resolve a singleton of type A with a parameter _A'_, then a singleton of type B with a parameter _B'_.

In the situation outlined above, **the container uses _A'_ to resolve B too!**

[Here's a .NET fiddle](https://dotnetfiddle.net/hSLcEo) evidencing the issue.

**Comment by dadhi** [comment] 2019-04-10 13:55
The behavior is by design - when you are making everything singleton, that means your `IName` instances also are `Singleton`. Therefore the first created instance with the provided argument will be reused for the subsequent resolutions ignoring the newly provided argument. It is fixed by making `IName` registration a `Transient`.

DryIoc is smart but not too smart in this case, otherwise, it should deal with the large Zoo of possible use-cases, which is basically a "magic" I wanted to avoid.

**Comment by rdeago** [comment] 2019-04-10 14:11
D'oh! _(slaps forehead)_

The fact that I was making `IName`s singletons totally escaped me.

Besides, I thought a singleton couldn't have transients injected. Is this a special case, or did I just misunderstand?

Thanks a lot!

**Closed** 2019-04-10 14:19 UTC

**Comment by dadhi** [comment] 2019-04-10 15:12
Transient may be injected into Singleton.. once. Transient just means that the service will be created anew whenever injected and does not care about the context: scoped, singleton or whatnot.
