### ISSUE TITLE
Func wrapper resolving

### ISSUE THREAD

**Issue by raV720** [dadhi/DryIoc#63] opened 2018-12-28 09:21 UTC
```
var container = new Container(rules: Rules.Default
                .WithUnknownServiceResolvers((request) => new DelegateFactory(_ =>  null)));

//container.Register<A>(); //UNCOMMENT THIS LINE TO GET EXCEPTION
var fFunc = container.Resolve<Func<IFoo>>();
var f0 = fFunc();//can be resolved as null because of unknown service resolver
container.Register<IFoo, Foo1>(reuse: Reuse.Singleton, ifAlreadyRegistered: IfAlreadyRegistered.Replace, setup: Setup.With(asResolutionCall: true));
var f1 = container.Resolve<IFoo>();
var f2 = fFunc();

Assert.IsNull(f0);
Assert.IsNotNull(f2);//EXCEPTION
Assert.AreEqual(f1, f2);
```
```

internal interface IFoo { }
internal class Foo1 : IFoo { }
internal class A
{
public A(Func<IFoo> func) { }
}
```

Why f2 is null after uncomment the line:` container.Register<A>()`

**Comment by dadhi** [comment] 2018-12-28 18:08
I am not sure, the `A` is not resolved by your example. Seems unrelated. Probably a bug. Will check.

**Comment by dadhi** [comment] 2019-02-09 13:53
Hi @raV720, 

The problem is the corner case with the cache, particularly the first added `A` registration triggered the caching of the first resolved `IFoo`.

Thanks for finding this issue, I was able to come with a more generic solution to control the cache for factories produced by `UnresolvedServiceResolvers` and dynamic registrations.

**Comment by dadhi** [comment] 2019-02-10 16:02
fixed.

**Closed** 2019-02-10 16:02 UTC
Labels: bug
