### ISSUE TITLE
Performance degradation with dymanic registrations in v4 compared to v2

### ISSUE THREAD

**Issue by yallie** [dadhi/DryIoc#417] opened 2021-07-13 00:26 UTC
Hi Maksim,

I've recently upgraded an application running DryIoc v2.12.6 to DryIoc v4.8.1   
and noticed substantial performance degradation (it runs about ~70x slower). 

The application is a simple intranet web server that hosts web APIs implemented as C# scripts.
Server loads scripts from the database and recompiles them on-the-fly when they are changed.
It uses DryIoc to wire them up to the built-in services and to the other scripts.
This feature relies on DryIoc's dynamic registrations.

I trimmed down the project to reproduce the isolated issue.
My benchmark basically imports and calls the same web service 1000 times in a row.
I also tested a v3 version of DryIoc to check if it performs any better.

Here is the log:

### v2.12.6.0

```log
D:\Externals\DryIocPerf\Bin\v2\net46>DryIoc2Perf.exe
[02:53:07 INF] Starting up...
[02:53:07 INF] Started.
[02:53:07 INF] Hello there. Starting the benchmark.
[02:53:07 INF] Imported web services: 104
[02:53:07 INF] GetNow: 2021-07-13T02:53:07.0000000+03:00
[02:53:07 INF] Warming up...
[02:53:08 INF] Running the benchmark...
[02:53:08 INF] Time elapsed: 00:00:00.0756021
```

### v3.0.2.0

```log
D:\Externals\DryIocPerf\Bin\v3\net46>DryIoc3Perf.exe
[02:53:13 INF] Starting up...
[02:53:14 INF] Started.
[02:53:14 INF] Hello there. Starting the benchmark.
[02:53:14 INF] Imported web services: 104
[02:53:14 INF] GetNow: 2021-07-13T02:53:14.0000000+03:00
[02:53:14 INF] Warming up...
[02:53:14 INF] Running the benchmark...
[02:54:20 INF] Time elapsed: 00:01:05.5922111
```

### v4.8.1.0

```log
D:\Externals\DryIocPerf\Bin\v4\net46>DryIoc4Perf.exe
[03:04:06 INF] Starting up...
[03:04:06 INF] Started.
[03:04:06 INF] Hello there. Starting the benchmark.
[03:04:06 INF] Imported web services: 104
[03:04:06 INF] GetNow: 2021-07-13T03:04:06.0000000+03:00
[03:04:06 INF] Warming up...
[03:04:06 INF] Running the benchmark...
[03:04:12 INF] Time elapsed: 00:00:05.4144036
```

* v4.8.1 performs ~72 times slower than v2.12.6
* v3.0.2 performs ~876 times slower than v2.12.6

~~Perhaps I'm doing something wrong in my dynamic registration resolver...~~
Upd. No, it seems to reproduce even if dynamic callback does nothing.

I'm going to clean up the code and upload it to a separate github repo.
The benchmark is actually quite small, but the dependencies are heavy.

**Comment by yallie** [comment] 2021-07-13 01:06
Benchmark code is located here: https://github.com/yallie/DryIocPerf
There are three projects for each DryIoc version, their code is almost identical.

**Comment by dadhi** [comment] 2021-07-13 03:12
@yallie Hi. Usually when you are coming back into the project, things improve :)

The dynamic registrations done differently since then, I am using the "real" registrations conparing to the unknown service resolver delegate in v2.
Plus I did not invest much time optimizing the dynamic scenario... will look now with your benchmark.

**Comment by yallie** [comment] 2021-07-13 10:10
Hi @dadhi, thank you :)

Looks like v4 calls dynamic registration lookup callback much more frequently than v2:

![image](https://user-images.githubusercontent.com/672878/125434299-72d53e6f-f5d0-45af-a019-2c2ecce8d8f1.png)

**Comment by dadhi** [comment] 2021-07-13 10:35
@yallie It is a great insite into the problem. I have started profiling but kind of suck in this topic...

Will check what's happening.

**Comment by dadhi** [comment] 2021-07-13 14:25
@yallie Seems I have found the main problem.

Previously there were no support for dynamic decorators (I've forgot to add them). So I've added them later with the ability to specify what is dynamic provider for: service, decorator, or both.
The 1st part of problem is that `service | decorator` is the default behavior, so every check for decorator will evaluate the dynamic provider. I think it is fine to revert to `service` as it was the older behavior with no complains. 

The 2nd part is that decorator resolver is not checking the dynamic provider `flags` anyway :)
It should be fixed.

Fixing...

Btw, found smaller perf. issues but it is probably for v5.

**Comment by yallie** [comment] 2021-07-13 15:32
That's awesome, Maksim! 👍

**Comment by yallie** [comment] 2021-07-13 15:48
Do we assume that during the current resolution the container doesn't change? Looks like yes, we do.

Then why do we inspect the list of ~40 service types over and over again calling the dynamic provider about ~2 million times? Every service type is asked for about ~50k times in average :)

Isn't it an option to just memoize and reuse the result of the dynamic registration provider call during the same resolution process? On the other hand, thoroughly optimized dynamic provider isn't much different from the memoized dynamic provider :)

I suspect that at least some of these 2 million calls of the dynamic resolver might not be necessary.

**Comment by dadhi** [comment] 2021-07-13 15:54
> I suspect that at least some of these 2 million calls of the dynamic resolver might not be necessary.

I suspect this too and will try to cut to absolute minimum. 
But generally the dynamic provider is treated as the black box possibly reconfigurable at runtime ("dynamic"). So the client should memoize on their end.

**Comment by yallie** [comment] 2021-07-13 17:00
> But generally the dynamic provider is treated as the black box possibly reconfigurable at runtime ("dynamic"). So the client should memoize on their end.

I understand that it's treated as a black box. But assuming it can yield different results during the same resolution is kinda weird... Do you see any possible application of this assumption, apart from crashing the host process? :)

I'd say it's safe to assume that during each particular resolution call dynamic resolver acts deterministically yielding the same results each time it's called. As if each resolution were instantaneous, capturing the state of the application at an exact moment.

**Comment by dadhi** [comment] 2021-07-13 17:07
Make sense. I need to think it through in the context of the dynamic provider api shape and the resolution pipeline.

**Comment by dadhi** [comment] 2021-07-14 13:50
@yallie Could you commit your changes with the dynamic lookup count?

**Comment by yallie** [comment] 2021-07-14 14:00
They are already there, see https://github.com/yallie/DryIocPerf/commit/ccc7790042323f8f1b8a4dd9b9e42c9cb9f70d01

**Comment by dadhi** [comment] 2021-07-14 16:03
@yallie Thanks, it was me not updating the GitHub page, forgot that GH is half-SPA app.

**Comment by yallie** [comment] 2021-07-17 11:53
Hi Maksim,

>fixing: #417 in V5;

Does this fix help to cut down the number of calls to the dynamic provider callback?
Any chance it's backportable to v4 branch?

**Comment by dadhi** [comment] 2021-07-17 12:44
@dadhi I have ported it back but it is still 110k instead of 290k calls. I will do some more.

**Comment by yallie** [comment] 2021-07-17 13:58
110k is so much better because my numbers were ~2900k, not 290k :)

**Comment by dadhi** [comment] 2021-07-19 14:35
@yallie 

> 110k is so much better because my numbers were ~2900k, not 290k :)

No, it was actually 1.1m.

I've improved it further to 330k, not good whatsover :/

So, as the next step I will add the cache for the dynamic factories into the resolution request.

**Comment by yallie** [comment] 2021-07-19 21:26
Hmm, that's weird...
The list of service types is cut down more than twice.
The number of calls of the dynamic provider is reduced tenfold!
But the time elapsed is actually larger than v4:

## v4

```c#
2021-07-17 22:00:49.020 +03:00 [INF] Starting up...
2021-07-17 22:00:49.473 +03:00 [INF] Started.
2021-07-20 00:16:23.836 +03:00 [INF] Starting up...
2021-07-20 00:16:24.754 +03:00 [INF] Started.
2021-07-20 00:16:24.864 +03:00 [INF] Hello there. Starting the benchmark.
2021-07-20 00:16:24.942 +03:00 [INF] Imported web services: 104
2021-07-20 00:16:24.991 +03:00 [INF] GetNow: 2021-07-20T00:16:24.0000000+03:00
2021-07-20 00:16:24.994 +03:00 [INF] Warming up...
2021-07-20 00:16:25.063 +03:00 [INF] Running the benchmark...
2021-07-20 00:16:32.125 +03:00 [INF] Time elapsed: "00:00:07.0588962"
2021-07-20 00:16:32.128 +03:00 [INF] Dynamic lookup count: 2902207
2021-07-20 00:16:32.434 +03:00 [INF] Succeeded lookup count: 107746
```

### types:

* DryIoc.Meta`2[System.Lazy`1[System.Func`1[Ultima.WebServices.IWebService]],Ultima.WebServices.IWebServiceMetadata]
* DryIoc.Meta`2[System.Lazy`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata]
* DryIoc.Meta`2[T,TMetadata]
* System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[System.Object,System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata]]]
* System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[System.Object,System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata]]]
* System.Collections.Generic.IEnumerable`1[System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata]]
* System.Collections.Generic.IEnumerable`1[System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata]]
* System.Collections.Generic.IEnumerable`1[T]
* System.Collections.Generic.KeyValuePair`2[System.Object,System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata]]
* System.Collections.Generic.KeyValuePair`2[System.Object,System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata]]
* System.Collections.Generic.KeyValuePair`2[TKey,TValue]
* System.Func`1[TResult]
* System.Func`1[Ultima.WebServices.IWebService]
* System.Lazy`1[System.Func`1[Ultima.WebServices.IWebService]]
* System.Lazy`1[T]
* System.Lazy`1[Ultima.Client.IUserMessages]
* System.Lazy`1[Ultima.IConstantManager]
* System.Lazy`1[Ultima.Linq.ITableSource]
* System.Lazy`1[Ultima.Log.ILogManager]
* System.Lazy`1[Ultima.Server.Data.ISqlService]
* System.Lazy`1[Ultima.WebServices.IWebService]
* System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata]
* System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata][]
* System.Lazy`2[T,TMetadata]
* System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata]
* System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata][]
* System.Object
* System.String
* Ultima.Client.IUserMessages
* Ultima.Dictionaries.IDictionaryManager
* Ultima.Documents.IDocumentManager
* Ultima.IConstantManager
* Ultima.Linq.ITableSource
* Ultima.Log.ILogger
* Ultima.Log.ILogger`1[T]
* Ultima.Log.ILogger`1[Ultima.WebServices.GetNow]
* Ultima.Log.ILogManager
* Ultima.Server.Composition.ServerCallImport`1[T]
* Ultima.Server.Composition.ServerCallImport`1[Ultima.WebServices.IPermissionService]
* Ultima.Server.Data.ISqlService
* Ultima.Server.WebServices.IRequestContextProvider
* Ultima.WebServices.IWebService

## Fix version

```c#
2021-07-20 00:18:54.133 +03:00 [INF] Starting up...
2021-07-20 00:18:54.456 +03:00 [INF] Started.
2021-07-20 00:18:54.540 +03:00 [INF] Hello there. Starting the benchmark.
2021-07-20 00:18:54.621 +03:00 [INF] Imported web services: 104
2021-07-20 00:18:54.668 +03:00 [INF] GetNow: 2021-07-20T00:18:54.0000000+03:00
2021-07-20 00:18:54.674 +03:00 [INF] Warming up...
2021-07-20 00:18:54.722 +03:00 [INF] Running the benchmark...
2021-07-20 00:19:02.164 +03:00 [INF] Time elapsed: "00:00:07.4390551"
2021-07-20 00:19:02.166 +03:00 [INF] Dynamic lookup count: 329068
2021-07-20 00:19:02.204 +03:00 [INF] Succeeded lookup count: 106740
```

### types

* System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata]
* System.Lazy`2[System.Func`1[Ultima.WebServices.IWebService],Ultima.WebServices.IWebServiceMetadata][]
* System.Lazy`2[T,TMetadata]
* System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata]
* System.Lazy`2[Ultima.WebServices.IWebService,Ultima.WebServices.IWebServiceMetadata][]
* Ultima.Client.IUserMessages
* Ultima.Dictionaries.IDictionaryManager
* Ultima.Documents.IDocumentManager
* Ultima.IConstantManager
* Ultima.Linq.ITableSource
* Ultima.Log.ILogger
* Ultima.Log.ILogger`1[T]
* Ultima.Log.ILogger`1[Ultima.WebServices.GetNow]
* Ultima.Log.ILogManager
* Ultima.Server.Composition.ServerCallImport`1[T]
* Ultima.Server.Composition.ServerCallImport`1[Ultima.WebServices.IPermissionService]
* Ultima.Server.Data.ISqlService
* Ultima.Server.WebServices.IRequestContextProvider
* Ultima.WebServices.IWebService

**Comment by yallie** [comment] 2021-07-20 21:33
Hi Maksim,

Sorry for bombing you with my pesky messages.

Out of curiosity, I tried to remove the dynamic resolver and compared normal container behavior.
Looks like v4 performs in my project ~50x slower than v2 even without dynamic registrations.

## v2

```c#
2021-07-21 00:11:26.987 +03:00 [INF] Starting up...
2021-07-21 00:11:27.334 +03:00 [INF] Started static benchmark.
2021-07-21 00:11:27.399 +03:00 [INF] Hello there. Static benchmark works fine.
2021-07-21 00:11:27.521 +03:00 [INF] Imported web services: 104
2021-07-21 00:11:27.569 +03:00 [INF] GetNow: 2021-07-21T00:11:27.0000000+03:00
2021-07-21 00:11:27.573 +03:00 [INF] Warming up...
2021-07-21 00:11:27.650 +03:00 [INF] Running the benchmark...
2021-07-21 00:11:27.737 +03:00 [INF] Time elapsed: "00:00:00.0833480"
```

## v4+fix

```c#
2021-07-21 00:09:12.375 +03:00 [INF] Starting up...
2021-07-21 00:09:12.720 +03:00 [INF] Started static benchmark.
2021-07-21 00:09:12.805 +03:00 [INF] Hello there. Static benchmark works fine.
2021-07-21 00:09:12.882 +03:00 [INF] Imported web services: 104
2021-07-21 00:09:12.933 +03:00 [INF] GetNow: 2021-07-21T00:09:12.0000000+03:00
2021-07-21 00:09:12.937 +03:00 [INF] Warming up...
2021-07-21 00:09:12.963 +03:00 [INF] Running the benchmark...
2021-07-21 00:09:17.015 +03:00 [INF] Time elapsed: "00:00:04.0487541"
```

In v2, both normal and dynamic registrations run for ~80ms.
In v4, normal registrations run for ~4s (dynamic registrations run for ~7s).

Perf. profiling shows that v4 calls are substantially different:

## v2

### call tree

![image](https://user-images.githubusercontent.com/672878/126397163-4217a3e7-99c2-4c33-a53b-8f7d66f18d88.png)

### call list (methods ordered by self-time)

![image](https://user-images.githubusercontent.com/672878/126397208-7c891056-9e50-4a69-a3f5-1b55cf299296.png)

## v4 hotfix

### call tree

![image](https://user-images.githubusercontent.com/672878/126397041-6f0c0db4-ba6a-4733-8719-b3e685e72f97.png)

### call list

![image](https://user-images.githubusercontent.com/672878/126397082-61407e73-6a95-4520-a1bb-31fcf3daebea.png)

What looks suspicious to me in the last picture:

* A lot of time is spent in `GetGenericMethodDefinition` and `MakeGenericMethod`.
* Huge hit count of the `.Match` lambda-function in `GetAllServiceFactories`.

**Comment by dadhi** [comment] 2021-07-21 04:19
@yallie Yes I've got a similar results, cutting the number of dynamic lookups to 17k with the help of cache. Number of call to GetExpression... is through the roof.

What profiler are using and what is the proflling mode.. because I can't figure it out with dotTrace except for the number of calls using Tracing?

And I doubt the it is Match or GetGenDefinition alone, because those are small comparing to the GetExpression begemot.

**Comment by dadhi** [comment] 2021-07-21 04:34
@yallie Btw, my current guess that the problem is the absence of caching for this specific case.
I have excluded number of problematic conditions from caching given that they **may** lead to the stale cache. So I think you are hitting one of those or the combination.

**Comment by yallie** [comment] 2021-07-21 07:59
>What profiler are using and what is the proflling mode.. because I can't figure it out with dotTrace except for the number of calls using Tracing?

I'm using [NProfiler](https://www.nprofiler.com/) in the tracing mode.
Tracing has large overhead, but it's more accurate than sampling and can register hit count.

>And I doubt it is Match or GetGenDefinition alone, because those are small comparing to the GetExpression begemot.

I was talking about their self-time (without child calls).

**Comment by yallie** [comment] 2021-07-21 13:49
>I have excluded number of problematic conditions from caching given that they 
>may lead to the stale cache. So I think you are hitting one of those or the combination.

It sounds like an easy thing to check. Can we disable these conditions to test your hypothesis?

**Comment by dadhi** [comment] 2021-07-23 04:29
@yallie Hello,

Currently the expressions cached only for services and not for wrappers, I experimented with it and number of tests start to fail, so it is for the reason. Though I am planning to look at it closer later. 
For now I am simplifying the story of combing dynamic and normal registrations, removing the one problem from the picture before diving back to the caching.

**Comment by yallie** [comment] 2021-08-19 09:20
Hi Maksim,

Is v2 resolution pipeline completely different than the one in v4?
What about trying to compare v2 execution flow to v4 to spot the problem, is it even possible?
Is there any way I can help you with resolving this issue?

**Comment by dadhi** [comment] 2021-08-19 13:04
I don't remember exactly the differences, I assume there are a lot of them.

This month I have moved from the one country to another and got the new work, so it was the lack of time to look further into the issue. Though I have some ideas to proceed. I hope that I can unblock myself soon to proceed, because it is fun  :)

**Comment by yallie** [comment] 2021-08-19 18:38
>This month I have moved from the one country to another and got the new work

That's great, my congrats! :)

>The help will be either suggesting the concrete fix without regression for the non-dynamic scenario or the actual implementation of this fix.

This issue has nothing to do with dynamic scenario. You can revert back the issue title :)
DryIoc v4 performs ~50-70 times slower than v2 in all scenarios in my test project.
Dynamic resolution, static resolution, resolve many, resolve single, anything.

Perhaps it has something to do with the size of the dependency graph.
Like some O(1) or O(ln(N)) code in v2 got replaced with O(N) or even O(N²) code in v4.

>Or maybe suggesting other/external ways of handling the situation.

I have a weird idea of getting DryIoc v2 core and upgrading the dependencies (ImTools, FEC) 
to their v4 counterparts and trying to see if we can make in work...

**Comment by dadhi** [comment] 2021-08-19 21:37
> DryIoc v4 performs ~50-70 times slower than v2 in all scenarios in my test project.

Interesting... show me non dynamic thing that slower, make as small as possible. Maybe we will  find the culprits faster.

> I have a weird idea of getting DryIoc v2 core and upgrading the dependencies (ImTools, FEC)

I would love to see such thing. It will be the first of its kind probably. Then I would've tested it against the current test suite to get the idea of the of the failing bunch - maybe it wont't be as essential as it seemed.

**Comment by yallie** [comment] 2021-08-19 23:50
>Interesting... show me non dynamic thing that slower, make as small as possible. Maybe we will find the culprits faster.

It's in my repo, see https://github.com/yallie/DryIocPerf/blob/master/Shared/SharedProgram.cs#L76

`StaticBenchmark` doesn't use dynamic resolution features.
It has only RegisterExports + InjectPropertiesAndFields.

>I would love to see such thing. It will be the first of its kind probably. Then I would've tested it against the current test suite to get the idea of the of the failing bunch - maybe it wont't be as essential as it seemed.

Alright then, let me try it out :)

**Comment by yallie** [comment] 2021-08-24 00:37
I've created a synthetic benchmark using a T4 template that generates interfaces and services.
It turns out DryIoc v4 is actually faster than DryIoc v2 in most use cases except for the one: import many.
Here is the example:

```c#
public class InjectPropertiesIntoThisClass
{
  [Import]
  private Lazy<IService>[] SlowImport { get; set; } 

  [Import]
  private Lazy<IService, IMetadata>[] VerySlowImport { get; set; }
}
```

But normal container.Resolve<Lazy<IService, IMetadata>[]>() is fast.
So I guess the problem is somewhere in MefAttributedModel.

**Comment by dadhi** [comment] 2021-08-24 19:51
@yallie This is a much more simplified case to dig. Thank you. Will look when time permits.

**Comment by yallie** [comment] 2021-08-24 20:43
Thanks a lot! 🎉

**Comment by dadhi** [comment] 2022-03-16 16:35
@yallie I have burned it down to the propagating of the already resolved `DynamicRegistration` factory  through the wrappers chain. 
But **it requires the explicit support** in the wrapper factory implementation.
Currently, the factory is propagated up to `Func/Action` with or without arguments and to `Lazy<T>` and `Lazy<T, TMeta>`.
The factory is propagated from and through the `Array` and collection wrappers, `KeyValuePair` and the `Meta/Tuple` wrappers.

`ExportFactory<T>` and `ExportFactory<T, TMeta>` is not supported yet. I postponing it for the next version or the PRs.

The factory won't propagate up-to **but not through** the `Lazy` and `Func` into the resolution calls - essentially it means the `DynamicRegistration` will be called again. It is because of the dynamic nature of those wrappers - they may be used for the late registration done after the wrappers are resolved but not yet consumed.

**Closed** 2022-03-16 16:36 UTC
Labels: performance
