### ISSUE TITLE
Xamarin Forms iOS System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by ChrisJAult** [dadhi/DryIoc#156] opened 2019-07-30 06:53 UTC
After upgrading to 4 from 3 registrations fail on iOS with System.PlatformNotSupportedException: Operation is not supported on this platform.

```
container.RegisterMany(new[] { typeof(CoreRegistry).GetTypeInfo().Assembly },
type => type.IsAssignableTo< IMenuProvider >(),
ifAlreadyRegistered: IfAlreadyRegistered.AppendNewImplementation);
```

I tried using .WithoutFastExpressionCompiler(); because JIT is not supported on iOS but the registration still threw the exception.

    Version with issue: 4
    Last known good version: 3
    Xamarin.Forms version: 3.6.0.344457
    IDE: Visual Studio 2019 Enterprise

**Comment by dadhi** [comment] 2019-07-30 07:22
What is the exception message and stacktrace in both cases?

**Comment by ChrisJAult** [comment] 2019-07-30 09:32
The exception is {System.PlatformNotSupportedException: Operation is not supported on this platform.  

This is the stack trace produced

`  at System.Reflection.Emit.DynamicMethod..ctor (System.String name, System.Type returnType, System.Type[] parameterTypes, System.Type owner, System.Boolean skipVisibility) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/src/Xamarin.iOS/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.notsupported.cs:64 
  at FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCompile (FastExpressionCompiler.LightExpression.ExpressionCompiler+ClosureInfo& closureInfo, System.Type delegateType, System.Type[] paramTypes, System.Type returnType, FastExpressionCompiler.LightExpression.Expression expr, System.Collections.Generic.IReadOnlyList`1[T] paramExprs, System.Boolean isNestedLambda) [0x00086] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at FastExpressionCompiler.LightExpression.ExpressionCompiler.TryCompile[TDelegate] (FastExpressionCompiler.LightExpression.Expression bodyExpr, System.Collections.Generic.IReadOnlyList`1[T] paramExprs, System.Type[] paramTypes, System.Type returnType) [0x0000a] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at FastExpressionCompiler.LightExpression.ExpressionCompiler.CompileFast[T1,R] (FastExpressionCompiler.LightExpression.Expression`1[TDelegate] lambdaExpr, System.Boolean ifFastFailedReturnNull) [0x00000] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at DryIoc.Portable.GetAssemblyTypesMethod () [0x000af] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <4b124141b7914f4d8253001e6b8a15cf>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <4b124141b7914f4d8253001e6b8a15cf>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <4b124141b7914f4d8253001e6b8a15cf>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <4b124141b7914f4d8253001e6b8a15cf>:0 
  at DryIoc.Portable.GetAssemblyTypes (System.Reflection.Assembly a) [0x00000] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at DryIoc.Registrator.GetImplementationTypes (System.Reflection.Assembly assembly) [0x00000] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00051] in <7c9d4d4f135d40b59732b673b488f4c5>:0 
  at DryIoc.Registrator.RegisterMany (DryIoc.IRegistrator registrator, System.Collections.Generic.IEnumerable`1[T] implTypes, System.Func`2[T,TResult] getServiceTypes, System.Func`2[T,TResult] getImplFactory, System.Func`3[T1,T2,TResult] getServiceKey, System.Nullable`1[T] ifAlreadyRegistered) [0x0007d] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at DryIoc.Registrator.RegisterMany (DryIoc.IRegistrator registrator, System.Collections.Generic.IEnumerable`1[T] implTypes, DryIoc.IReuse reuse, DryIoc.Made made, DryIoc.Setup setup, System.Nullable`1[T] ifAlreadyRegistered, System.Func`2[T,TResult] serviceTypeCondition, System.Boolean nonPublicServiceTypes, System.Object serviceKey) [0x00034] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at DryIoc.Registrator.RegisterMany (DryIoc.IRegistrator registrator, System.Collections.Generic.IEnumerable`1[T] implTypeAssemblies, System.Func`2[T,TResult] serviceTypeCondition, DryIoc.IReuse reuse, DryIoc.Made made, DryIoc.Setup setup, System.Nullable`1[T] ifAlreadyRegistered, System.Boolean nonPublicServiceTypes, System.Object serviceKey) [0x0001d] in <030e4f7b0206410ba41a3c4edd8cfe41>:0 
  at River.Bed.Mobile.Core.Ioc.CoreRegistry.Load (Prism.Ioc.IContainerRegistry containerRegistry) [0x00108] in E:\Repositories\River.Bed.Mobile\Mobile\River.Bed.Mobile\Core\Ioc\CoreRegistry.cs:39 
  at River.Bed.Mobile.App.RegisterCoreTypes (Prism.Ioc.IContainerRegistry containerRegistry) [0x00001] in E:\Repositories\River.Bed.Mobile\Mobile\River.Bed.Mobile\App.xaml.cs:137 
  at River.Bed.Mobile.Client.ClientApp.RegisterCoreTypes (Prism.Ioc.IContainerRegistry containerRegistry) [0x00001] in E:\Repositories\River.Bed.Mobile\Clients\RiverBlue\River.Bed.Mobile.Client\ClientApp.cs:33 
  at River.Bed.Mobile.App.RegisterTypes (Prism.Ioc.IContainerRegistry containerRegistry) [0x00001] in E:\Repositories\River.Bed.Mobile\Mobile\River.Bed.Mobile\App.xaml.cs:131 
  at Prism.PrismApplicationBase.Initialize () [0x0002f] in d:\a\1\s\Source\Xamarin\Prism.Forms\PrismApplicationBase.cs:133 
  at Prism.PrismApplicationBase.InitializeInternal () [0x00006] in d:\a\1\s\Source\Xamarin\Prism.Forms\PrismApplicationBase.cs:84 
  at Prism.PrismApplicationBase..ctor (Prism.IPlatformInitializer platformInitializer, System.Boolean setFormsDependencyResolver) [0x00038] in d:\a\1\s\Source\Xamarin\Prism.Forms\PrismApplicationBase.cs:75 
  at Prism.PrismApplicationBase..ctor (Prism.IPlatformInitializer platformInitializer) [0x00000] in d:\a\1\s\Source\Xamarin\Prism.Forms\PrismApplicationBase.cs:57 
  at Prism.DryIoc.PrismApplication..ctor (Prism.IPlatformInitializer platformInitializer) [0x00000] in d:\a\1\s\Source\Xamarin\Prism.DryIoc.Forms\PrismApplication.cs:34 
  at River.Bed.Mobile.App..ctor (Prism.IPlatformInitializer initializer) [0x00000] in E:\Repositories\River.Bed.Mobile\Mobile\River.Bed.Mobile\App.xaml.cs:52 
  at River.Bed.Mobile.Client.ClientApp..ctor (Prism.IPlatformInitializer initializer) [0x00000] in E:\Repositories\River.Bed.Mobile\Clients\RiverBlue\River.Bed.Mobile.Client\ClientApp.cs:20 
  at River.Bed.Mobile.Client.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x0009b] in E:\Repositories\River.Bed.Mobile\Clients\RiverBlue\River.Bed.Mobile.Client.iOS\AppDelegate.cs:74 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.110/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at River.Bed.Mobile.Client.iOS.Application.Main (System.String[] args) [0x00001] in E:\Repositories\River.Bed.Mobile\Clients\RiverBlue\River.Bed.Mobile.Client.iOS\Main.cs:17 `

**Comment by dadhi** [comment] 2019-07-30 09:43
Thank you,
It will be fixed with #90 / I hope to roll out it soon.

**Comment by ChrisJAult** [comment] 2019-07-30 09:50
Great, thanks :)

**Comment by dadhi** [comment] 2019-08-21 19:17
The v4.1.0-preview-01 is out with `Rules.WithUseInterpretation()` option. 
Try it out for iOS target.

**Comment by xleon** [comment] 2019-09-16 14:33
I had the same issue and the latest version fixed it

**Comment by dadhi** [comment] 2019-09-16 15:30
@xleon ,

Thanks, good news.

**Comment by nukefusion** [comment] 2020-05-21 09:46
This isn't fixed. On iOS on version 4.2 of the package, RegisterMany will just not work, even with .WithUseInterpretation and .WithoutFastExpressionCompiler.

**Comment by dadhi** [comment] 2020-05-21 10:33
@nukefusion 

> This isn't fixed. On iOS on version 4.2 of the package, RegisterMany will just not work, even with .WithUseInterpretation

Could provide a small reproduction sample?

**Comment by MilKAOS** [comment] 2020-06-05 10:03
Because we have the same issue I made you a small test project.
The solution is based on the standard Xamarin.Forms Master-Detail template for Android+iOS.
I only added DryIoc via the DryIoc.Microsoft.DependencyInjection package (DryIoc version is 4.1.4 
then) and the initialization of DryIoc with a not so meaningful registration.

The program will run on the Android emulator but not on the iOS simulator with the above mentioned error.
In our case we are currently still using a much older version of DryIoc to avoid the issue with iOS.

[DryIocTest.zip](https://github.com/dadhi/DryIoc/files/4735307/DryIocTest.zip)

**Comment by dadhi** [comment] 2020-06-05 10:36
@MilKAOS Thanks for the sample. Will look.

**Comment by dadhi** [comment] 2020-06-08 10:08
@MilKAOS 

![image](https://user-images.githubusercontent.com/39516/84018758-0e139700-a989-11ea-9765-95795f534f0f.png)

I don't have a Mac, so do we have any other workaround to debug the sample?

**Comment by dadhi** [comment] 2020-06-08 10:15
@MilKAOS Nevermind seems like I have found the problem. The problem is `GetAssemblyTypes()` is being called from `RegisterMany` is using dynamic ILEmit compilation for all platforms. Fix is in progress...

Btw, it also means that current workaround is avoiding `RegisterMany`.

**Comment by MilKAOS** [comment] 2020-06-08 13:21
@dadhi Unfortunately building for iOS needs the hardware. But I am glad that you found the issue!

**Comment by dadhi** [comment] 2020-06-08 20:15
DryIoc v4.2.1 is released with the bug-fix

**Comment by MilKAOS** [comment] 2020-06-09 12:19
Just to add to the fix as tip for all who might read the issue in the future:
For our apps it works with v4.2.1 for iOS but I had additionally to deactivate the FastExpressionCompiler.

**Comment by dadhi** [comment] 2020-06-09 12:37
@MilKAOS So `WithUseIbnterpretation` was not enough?

**Comment by MilKAOS** [comment] 2020-06-09 13:22
@dadhi My bad. WithUseInterpretation works too and then you don't need the FastExpressionCompiler deactivation.

**Comment by dadhi** [comment] 2020-06-09 14:43
That's cool to hear,
 because `WithoutFEC` is a rather complex and quirky feature to support.. 
Interpretation on the other hand is much more general and handy thing overall. So in V5 `WithoutFEC` will be Obsolete, then it will be removed later.

**Comment by dadhi** [comment] 2020-06-09 16:09
@MilKAOS I also wanted to ask is there any feature toggle either in runtime or compile-time `#ifdef` to find out the platform you are on?
I mean how to conditionally add `.WithUseInterpretation` for the iOS only?

I need this to be able to answer the questions and probably to put it somewhere in docs.

**Comment by MilKAOS** [comment] 2020-06-09 18:23
Xamarin.iOS should have `__IOS__` for conditional compilation but personally I never used it.
[Conditional Compilation](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation#conditional-compilation)

In our applications we are using Device.RuntimePlatform from Xamarin.Forms.
[RuntimePlatform](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/device)

**Comment by dadhi** [comment] 2020-06-09 18:25
Thanks!

**Comment by OmidID** [comment] 2020-11-12 10:21
@dadhi You could have Mac as virtual machine for test 
https://techsprobe.com/install-macos-big-sur-on-virtualbox-on-windows-pc/

**Comment by dadhi** [comment] 2020-11-12 10:47
@OmidID Hi, thanks for the link.

For the issue itself - is it something not working for you yet?

**Comment by OmidID** [comment] 2020-11-12 16:44
Yes. Same problem. On my side work only without fast compiler.
Maybe you could do some test with a virtual machine

**Comment by dadhi** [comment] 2020-11-12 17:40
@OmidID What DryIoc version do you use?

**Comment by OmidID** [comment] 2020-11-12 17:58
@dadhi The version I use is 4.5.1
I have another crash without any log!!!! so i found to changed one of the services from transient to scope and **solved**.
The interesting part it was try-catch couldn't catch it !!! I try to step into and then I reached to https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.cs#L551 and the app close without any error or log or anything. I never saw something similar before.

**Comment by dadhi** [comment] 2020-11-12 19:24
@OmidID 

Did it crash with or `WithoutFastExpressionCompiler`? 
And did you use `WithUseInterpretation()` or not?

**Comment by OmidID** [comment] 2020-11-13 11:20
Yes with WithoutFastExpressionCompiler and not WithUseInterpretation

```
            _container = new DryIoc.Container(rules =>
                rules.WithTrackingDisposableTransients()
                     .WithoutFastExpressionCompiler());

```

**Comment by dadhi** [comment] 2020-11-13 11:42
@OmidID Try to add the interpretation too, because otherwise you are using System Compile and it may not work on the platform.

**Comment by OmidID** [comment] 2020-11-13 13:22
I imagine this is should be done for iOS only. Right? for Android do I need the same options?

**Comment by dadhi** [comment] 2020-11-13 17:12
@OmidID For iOS only. Try to use default settings for Android.

I am very curious how is the FastExpressionCompiler relates to the problem, because WithUseInterperation don't assume the compilation.
The only thing I can imagine (except the bug) that the compilation used as a fallback when interpretation is failing, hmm...

I need probably to disable the fallback bacause it does not help when interpretation is the only option, and throw the relevant exception to make the problem visible.

**Comment by xleon** [comment] 2021-02-15 14:47
I'm considering to introduce DryIoC on a big Xamarin project soon. 
RegisterMany would be awesome to get rid of some nasty factories we have at the moment. 
Is there any more progress on this issue?

**Comment by dadhi** [comment] 2021-02-15 15:51
@xleon I think that generally everything works, just keep in mind to set `WithUseInterpretation()` rule for iOS.

This issue is open to think and decide on should the interpretation have the compilation fallback or just fail. And this a thing only if you ars using custom ExpressionFactory with the exotic expression not supported by the DryIoc interpreter.

My current choice is probably let it fail, because this is likely the indication of the client setup problem. Hiding it will produce more pain than profit.

**Comment by OmidID** [comment] 2021-02-15 18:16
@xleon FYI:  we are using DryIoc in a big project. After migration, we have better performance and lower memory usage. 

Using Scope over (ViewController(iOS), Activity(Android), Page(XF))

**Comment by xleon** [comment] 2021-02-16 07:21
@dadhi @OmidID I will give it a try. Thank you.

**Closed** 2021-02-16 10:20 UTC
Labels: bug, enhancement
