### ISSUE TITLE
IServiceCollection populate doe not work!

### ISSUE THREAD

**Issue by NimaFx** [dadhi/DryIoc#369] opened 2021-02-06 06:56 UTC
Hey DryIoc

```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
  var container = new Container();
  container.Populate(services);

  return container ;
}
```

And the result is! **Unable to select single public constructor from implementation type Microsoft.AspNetCore.Http.HttpContextFactory**

PS: It's netcoreapp2.1, DryIoc 4.2.7 and DryIoc.Microsoft.DependencyInjection 5.1.0

**Comment by dadhi** [comment] 2021-02-06 08:19
I will check but the versions are older, and I appreciate some digging done from your side, e.g. does the HttpContextFactory has no public ctors, etc. Maybe asking on SO will help too.

**Comment by NimaFx** [comment] 2021-02-06 10:48
I didn't use HttpContextFactory of HttpContext anywhere directly but its Microsoft.AspNetCore.Http.HttpContextFactory and have a public constractor with a depenecy to IOptions<FormOptions> 

I used an alternative method and it worked.
`var container = new Container().WithDependencyInjectionAdapter(services);`

**Comment by dadhi** [comment] 2021-02-06 15:57
@NimaFx Ah, ok.
That did not work because the container was not setup properly for MS.DI and was a bare `var container = new Container();`

You need to apply the MS.DI rules via `var container = new Container(rules => rules.WithMicrosoftDependencyInjectionRules());`
or use the `WithDependencyInjectionAdapter` as you did.

**Comment by NimaFx** [comment] 2021-02-07 12:08
Thank you, I got another issue.  It's hard to setup when one came from another container! But performance is significant! 

```
container.Register<IActionBehaviorContext, ActionBehaviorContext>(reuse: Reuse.Scoped);
container.RegisterDelegate(typeof(IActionBehavior) , request =>  factory(request) ,  Setup.With(openResolutionScope: true, useParentReuse: true));

using (var nested = container.CreateChild(ifAlreadyRegistered:IfAlreadyRegistered.Replace))
{
    var s1 = nested.Resolve<IActionBehaviorContext>();
    var s2 = nested.Resolve<IActionBehavior>();
     Assert.AreSame(s1, s2.Context); //failed, with my reasoning they should be same!
    //factory resolve IActionBehaviorContext with help of request
}
```
PS: Sorry, I guess it's not the right place to ask this. But I'm in a rush!! I chose the fasted method :D

**Comment by dadhi** [comment] 2021-02-07 13:34
@NimaFx I have a lor of questions to this setup:
1. Why `CreateChild` and not the `OpenScope`?
2. Why `openResolutionScope: true`?
3. What is the end goal of this setup?

**Comment by NimaFx** [comment] 2021-02-07 14:45
- There are a few registrations for the child container so, I intuitively thought it should be a child, not a scoped container. 

```
nested.RegisterInstance<ISession>(new Session()); //should replaced the with parent registration
nested.RegisterInstance<OwinContext>(_owinContext);
nested.RegisterInstance<RouteData>(_routeData);
```
Constructor of ActionBehaviorContext:
`  public ActionBehaviorContext(ISession session, OwinContext owinContext,RouteData routeData  ) {}`

Also, ActionBehaviorContext contains a Dictionary for sharing data within a child container.

- Without openResolutionScope it raises ContainerException: code: Error.NoCurrentScope

- The factory is a function created from an expression tree and it returns a graph of chained objects, so it requires the container for resolving dependencies (hopefully, same nested). In the previous version, we used ConfiguredInstance of structure-map to setup how these graphs of objects should resolve. but for reducing dependency on a specific container we changed it with this factory function

So inside the child container, all objects should receive the same ActionBehaviorContext.

**Comment by dadhi** [comment] 2021-02-07 19:07
@NimaFx I wrote a simplified version of your setup and it did not for past this line: https://github.com/dadhi/DryIoc/blob/eff9aba458b98767fa5fae7c42b6001e0143bc6d/test/DryIoc.IssuesTests/GHIssue369_Child_container_and_openResolutionScope_in_one_test.cs#L40

So I am not sure how is your setup was able to.

I suggest you start from something more simple (similar to my test) and test your expectations before going full throttle.

**Comment by NimaFx** [comment] 2021-02-08 06:10
@dadhi  I did another test to make things simple:
` public DryIocServiceLocator(IResolverContext container) {}`

Both registrations for DryIocServiceLocator should have the same result.
```
container.RegisterDelegate<IServiceLocator>(resolver => new DryIocServiceLocator(resolver));
container.Register<IServiceLocator, DryIocServiceLocator>();
```
But these Resolvers have different scopes in a nested container.

**Comment by dadhi** [comment] 2021-02-08 06:16
@NimaFx I still don't understand what are you doing with this, please provide a complete test / example.. check my test again. That's what I need to make sense of it.

**Comment by NimaFx** [comment] 2021-02-08 11:23
@dadhi I was on the wrong assumption! I thought CreateChild creates a new scope but it won't!

```
  public interface IServiceLocator
    {
        IResolverContext Resolver { get; }
    }

    public class DryIocServiceLocator : IServiceLocator
    {
        public DryIocServiceLocator(IResolverContext resolver)
        {
            Resolver = resolver;
        }

        public IResolverContext Resolver { get; }
    }


    public interface IContext
    {
        Session Session { get; }
    }


    public class Context : IContext
    {
      
        public Context(Session session)
        {
            Session = session;
        }

        public Session Session { get; }
    }

   

    public class Session 
    {
        public int Code { get; set; }
        public Session()
        {
            Code = new Random().Next(99999999);
        }
    }


    public class DryIocSpec
    {
        [Fact]
        public void Should_resolve_context_child_container()
        {
            var container = new Container();

            container.RegisterDelegate<IServiceLocator>(resolver => new DryIocServiceLocator(resolver));
            container.Register<IContext,Context>(Reuse.Scoped);

            using (var nested = container.CreateChild())
            {
                nested.RegisterInstance<Session>(new Session());

                var context1 = nested.Resolve<IContext>();  // no scope exception
                var context2 = nested.Resolve<IServiceLocator>().Resolver.Resolve<IContext>(); // no scope exception

                context1.Should().Be(context2); 
            }

        }



        [Fact]
        public void Should_resolve_context_from_the_new_scope()
        {
            var container = new Container();

            container.Register<IServiceLocator, DryIocServiceLocator>();
            container.RegisterInstance<Session>(new Session());

            using (var nested = container.CreateChild(ifAlreadyRegistered: IfAlreadyRegistered.Replace))
            {
                nested.RegisterInstance<Session>(new Session());

                using (var inner = nested.OpenScope())
                {
                    var session1 = nested.Resolve<Session>();
                    var session2 = nested.Resolve<IServiceLocator>().Resolver.Resolve<Session>();

                    session1.Should().Be(session2); //pass
                }
            }
        }
    }
```

PS: no need to openResolutionScope: true anymore!

**Comment by dadhi** [comment] 2021-02-08 14:22
@NimaFx 

> CreateChild creates a new scope but it doesn't!

Yes, it is separate concept to scoping, but both can be combined together.

So the second test is passing and you are fine now?

**Comment by NimaFx** [comment] 2021-02-09 06:23
@dadhi thank you so much for your time. everything seems good so far. I guess It happens when one relying too much on pattern recognition! ;)

**Comment by dadhi** [comment] 2021-02-09 06:36
Good, I will put your last test into the regression suit then will close the issue.

**Closed** 2021-02-09 19:14 UTC
