### ISSUE TITLE
Original stack trace is lost at Interpreter.TryInterpretAndUnwrapContainerException

### ISSUE THREAD

**Issue by ryoasai** [dadhi/DryIoc#250] opened 2020-03-29 04:55 UTC
I had a trouble while debugging a thread safety problem of **my code**.

When executing all test cases, one of my test case failed with the following exception:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 2709
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 9484
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 9440
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 388
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 353
   at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType) in C:\projects\dryioc-qt8fa\src\DryIoc\Container.cs:line 7325
   at Prism.DryIoc.Ioc.DryIocContainerExtension.Resolve(Type type)
   at Prism.Ioc.IContainerProviderExtensions.Resolve[T](IContainerProvider provider)
```
But when I execute the failed test case, it somehow passed.

At first I had a fooled impression that the problem is in DryIoc code, but after digging into the problem, I found the NullRefereneException was thrown in Dictionary class. It was my fault that I was using the plain Dictionary class as a cache. Replacing it with CuncurrentDictionary solved the problem.

That's ok but a annoyingly that the original exception stack trace is lost at the following code:

```
          public static bool TryInterpretAndUnwrapContainerException(
            IResolverContext r, Expression expr, bool useFec, out object result)
        {
            try
            {
                return Interpreter.TryInterpret(r, expr, FactoryDelegateCompiler.ResolverContextParamExpr, r, null, useFec, out result);
            }
            catch (TargetInvocationException tex) when (tex.InnerException != null)
            {
                // restore the original excpetion which is expected by the consumer code
                throw tex.InnerException; // Original stack trace is lost here, make it hard to debug.
            }
        }

```

So it's not a DryIoC's bug per se but I think it's better that it will report the original stack trace to help debugging.

There seems to be a technique to keep the original stack trace, for example:

[https://stackoverflow.com/questions/57383/how-to-rethrow-innerexception-without-losing-stack-trace-in-c]()

Can you take a look at this problem?
I'm currently using v4.1.3.

**Comment by dadhi** [comment] 2020-03-29 07:41
@ryoasai This is a good catch!
I will add the fix into the next minor version.

**Comment by raV720** [comment] 2024-11-26 11:36
I have the same issue on MAUI when simply calling: Resolve(). The stack trace:

```
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
```

The service is registred like: `container.Register<IStartupService, StartupService>(reuse: Reuse.Singleton);`
The exception is thrown just inside ctor of StartupService.
DryIoc.dll version: 5.4.3
DryIoc.Microsoft.DependencyInjection version: 6.2.0

**Comment by dadhi** [comment] 2024-12-04 10:56
@raV720 Can you check the latest preview versions of the DryIoc.Microsoft.DependencyInjection and DryIoc.dll?

**Comment by raV720** [comment] 2024-12-05 08:33
I guess it is a problem with VisualStudio. I was diagnosing the problem using VisualStudio watch. Now I see the watch shows different values depending on how the property is displayed. When expanding exception properties in watch the value is wrong. But when referencing property directly the value of StackTrace contains the information about the location:

![Clipboard06](https://github.com/user-attachments/assets/01021c3f-dd2c-4464-a0e0-037bc479b5d1)

So finally after writing to logs the StackTrace is:

```
   at EMOBILE.Services.StartupService..ctor(IAppStateService appState, IOnlineService onlineService)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object&amp; result) in /_/src/DryIoc/Container.cs:line 3110
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11136
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11055
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 426
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 392
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8602

```

All without changing version of dryioc.
Thank you for support.

**Comment by dadhi** [comment] 2024-12-05 08:58
@raV720 So the problem is solved?

**Comment by raV720** [comment] 2024-12-05 09:01
Yes, actually there was no problem from dryioc side :)
Only from Visual Studio

**Comment by dadhi** [comment] 2024-12-05 09:19
Great for me. Closing it.

**Closed by dadhi** 2024-12-05 09:19 UTC
